# Project information
site_name: Nana - Modern C++ GUI
site_description: NGX (Nana) is a cross-platform library for GUI programming in modern C++ style.
site_author: Ludwig Fuechsl
copyright: >- 
  &copy; Copyright 2023 : Moxibyte GmbH and invididual nana-ngx.com contributors <br/>
  &copy; Copyright 2017 - 2022 : Jinhao and invididual nanapro.org contributors 

# GitHub repository link
repo_url: https://github.com/moxibyte/nana-ngx
edit_uri: blob/main/documentation

# TODO: Deploy options

# File locations
docs_dir: documentation

# Navigation
nav:
  - Nana:
    - About: "index.md"
    - Features: "features.md"
    - Get Help: "gethelp.md"
    - Support Us: "support.md"
    - Roadmap to v1.8-LTS: "roadmap-18.md"
    - Roadmap to v2.0: "roadmap-20.md"
    - License: "license.md"
  - Reference: "reference/index.md"
  - Examples: "examples/index.md"
  - Extend Nana: "extend/index.md"

# Markdown extensions
markdown_extensions:
  # Checked list
  - pymdownx.tasklist:
      custom_checkbox: true
  # Code hilight
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # Footnotes
  - footnotes
  # admonition (Alerts)
  - admonition
  - pymdownx.details
  # Icons
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


# Visual customisation
theme:
  name: material
  
  # Customize
  icon:
    logo: material/dock-window
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - content.code.copy

  # Light and Dark mode
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Cookie consent
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
